FLASK_DEBUG = on
FLASK_APP = app
PYTHONDONTWRITEBYTECODE = 1
GAMIL_ACC_PASS = 
GMAIL_ACCOUNT =
SECRET_KEY = F96438CDEC94D3C4E58D3F8A98345
GOOGLE_CLIENT_SECRET=
SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:@localhost/covid
GOOGLE_CLIENT_ID=
REDIS_URL = 

